### PR TITLE
Migration from Grunt 0.3 to Grunt 0.4

### PR DESCRIPTION
**Pull request by c9s**
Some fixes for Grunt 0.4

I suggest to merge this changes in another branch like "grunt-0.4" or something.

### CODE REVIEW

**Comment by jzaefferer** [comment]
Thanks for the contribution! Would you have a chance to update this to get rid of grunt-lib-legacyhelpers?

**Comment by c9s** [comment]
This patch uses grunt-lib-legacyhelpers. it's used by Grunt.js 0.4.x.  helper methods were moved out from gruntjs core. so we need to use grunt-lib-legacyhelpers in the future.

Please check this out.

https://github.com/gruntjs/grunt/wiki/Upgrading-from-0.3-to-0.4

**Comment by jzaefferer** [comment]
Right, but it should be possible to just replace the helper with some custom code. Its not terribly complicated and can probably be simplified for what we actually need here: https://github.com/gruntjs/grunt-lib-legacyhelpers/blob/9d1bd4f67ee9911b0d8a40d480742ce3bf8798de/lib/legacyhelpers.js#L17

**Comment by c9s** [comment]
Or do you mean write a grunt-css owned helper exporter ? 

yes, if I have a change.

**Comment by jzaefferer** [comment]
Yeah, just use something line, similar to this replacement of the min_max_info helper: d866a28c8391ec1fa2b86112a04ae3a3c383fe0e

**Comment by c9s** [comment]
I got it. Sure, but i am currenty too busy to do it.

Hope i will have a chance in later weeks. :-)

Jörn Zaefferer 於 2012年12月20日星期四寫道：

> Yeah, just use something line, similar to this replacement of the
> min_max_info helper: d866a28https://github.com/jzaefferer/grunt-css/commit/d866a28c8391ec1fa2b86112a04ae3a3c383fe0e
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jzaefferer/grunt-css/pull/17#issuecomment-11538877.

## 

Best Regards,

Yo-An Lin

**Comment by jzaefferer** [comment]
I've went ahead and got rid of the legacy helpers. The jshint task still doesn't actually validate a single file, can't figure out what's wrong there. But linting and minifying works, published 0.4 in 42a7c1abf1c4f0df9d843493707936df03a106a7

**Comment by jzaefferer** [comment]
Squashed your two commits into one here: dd760fa9389aa830573f456132824cfe69d21b75

**Pull request closed without merging**
