### PR TITLE
Fixing bugs for grunt 0.4.0rc2

### PR DESCRIPTION
**Pull request by c9s**
Hi,

Please check if this makes sense to you.

Thanks

### CODE REVIEW

**Comment by c9s** [comment]
Please see if this patch works for you. it works for me @ grunt 0.4.0~rc2

**Comment by jzaefferer** [comment]
The relevant versions to test against are currently 0.4.0rc5, and, if backwards compability should be added, 0.3.17. 0.4.0rc2 doesn't matter, as the final 0.4 will likely be as rc5 is now.

0.5.3 works with rc5, while 0.4.x works with grunt 0.3.x.

**Comment by c9s** [comment]
ok cool, so we don't need this?

**Comment by jzaefferer** [comment]
Nope, I don't think so. If you find any issues with rc5 (or final) though, let me know. Thanks.

**Pull request closed without merging**
